# Generated by Django 4.1.7 on 2024-01-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sonarqube',
            name='health',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sonarqube',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sonarqube',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
