# Generated by Django 4.1.7 on 2024-01-02 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sonar', '0002_alter_sonarqube_health_alter_sonarqube_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sonarqube',
            name='total_projects',
        ),
    ]
