# Generated by Django 4.1.7 on 2024-01-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonar', '0003_remove_sonarqube_total_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='sonarqube',
            name='version',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
