# Generated by Django 4.1.7 on 2023-12-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gitlab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitlab',
            name='version',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
