# Generated by Django 4.1.7 on 2023-12-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jenkins_servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenkins_servers',
            name='network_latency',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jenkins_servers',
            name='response_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jenkins_servers',
            name='server_up_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jenkins_servers',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
